services:
  db:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: example
    # ports:
    #   - "3306:3306"
    volumes:
      - data:/var/lib/mysql
  api:
    build: ./prayerAPI
    links:
      - db
    ports:
      - "5000:5000"
  frontend:
    build: ./prayer-react
    links:
      - api
    ports:
      - "3000:3000"
volumes:
  data:
